# Generated by Django 2.1.7 on 2019-04-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0004_pan_registration_model_pan_verification_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhar_registration_model',
            name='dob',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='aadhar_verification_model',
            name='dob',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pan_registration_model',
            name='dob',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pan_verification_model',
            name='dob',
            field=models.CharField(max_length=50),
        ),
    ]
