# Generated by Django 2.1.7 on 2019-04-05 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0006_userprofileinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='username',
            new_name='im_username',
        ),
    ]
