# Generated by Django 2.1.7 on 2019-04-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0007_auto_20190405_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='im_username',
            field=models.CharField(max_length=100),
        ),
    ]
