# Generated by Django 2.1.7 on 2019-04-05 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0008_auto_20190405_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='im_username',
        ),
    ]
