# Generated by Django 2.1.7 on 2019-04-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0011_auto_20190405_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_rating', models.FloatField(default=2)),
                ('investee_rating', models.FloatField(default=2)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
