# Generated by Django 2.1.7 on 2019-04-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0013_rating_active_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sub_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='rating',
        ),
    ]
